name: AOSPA Marble GKI (KernelSU Next)
on:
  workflow_dispatch:
env:
  CLANG_DIR: clang-r510928
jobs:
  build-kernel:
    runs-on: ubuntu-22.04
    steps:
#      - name: Free disk space
#        if: ${{ true }}
#        uses: jlumbroso/free-disk-space@main
#        with:
#          tool-cache: true
#          android: true
#          dotnet: true
#          haskell: true
#          large-packages: true
#          docker-images: true
#          swap-storage: false
      - name: Set swap space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 16
      - name: Increase file limit
        run: |
          sudo sysctl -w vm.swappiness=100
      - name: Check repository
        uses: actions/checkout@v6.0.2
        with:
          path: aospa-marble-gki-kernel
      - name: Setup Python
        uses: actions/setup-python@v6.2.0
        with:
          python-version: '3.x'
      - name: Setup build environment
        run: |
          sudo apt-get update
          sudo apt-get install -y curl git ccache pngcrush schedtool maven lib32ncurses5-dev xsltproc libxml2-utils squashfs-tools lzop flex build-essential bc libssl-dev libswitch-perl libxml-simple-perl zip unzip g++-multilib bison gperf zlib1g-dev automake device-tree-compiler
          sudo curl --create-dirs -o /usr/local/bin/repo -L https://storage.googleapis.com/git-repo-downloads/repo
          sudo chmod a+rx /usr/local/bin/repo
      - name: Clone repo and sync
        run: |
          repo init -u https://github.com/alex18101985/aospa-marble-gki-kernel -b "$(git -C aospa-marble-gki-kernel branch --show-current)" -m manifest.xml --depth=1
          repo sync
          mkdir -p kernel_platform/device/xiaomi/marble-kernel/dtbs
      - name: Cache Clang
        uses: actions/cache@v5.0.4
        with:
          path: kernel_platform/clang
          key: clang-r510928
      - name: Setup Clang
        run: |
          mkdir -p kernel_platform/clang
          cd kernel_platform/clang
          if [ ! -d "${CLANG_DIR}" ]; then
            echo "Clang not found in cache. Downloading..."
            git clone -n --depth=1 --filter=tree:0 -b main-kernel-build-2024 --single-branch \
              https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86 .
            git sparse-checkout init --cone
            git sparse-checkout set ${CLANG_DIR}
            git checkout
          else
            echo "Using cached ${CLANG_DIR}"
          fi
      - name: Include KernelSU Next
        run: |
          cd kernel_platform/xiaomi/sm8450
          rmdir KernelSU
          curl -LSs "https://raw.githubusercontent.com/KernelSU-Next/KernelSU-Next/next/kernel/setup.sh" | bash -s dev
      - name: Patch with custom configuration
        run: |
          cp -rvf aospa-marble-gki-kernel/android_kernel_xiaomi_sm8450/. kernel_platform/xiaomi/sm8450
          cd kernel_platform/xiaomi/sm8450
          patch -p1 < no-strict-error.patch
      - name: Build kernel
        run: |
          cd kernel_platform/xiaomi/sm8450
          export PATH=$PWD/kernel_platform/clang/${CLANG_DIR}/bin:$PATH
          ./build.sh marble --only-kernel
      - name: Zip kernel
        run: |
          git clone --depth=1 -b master https://github.com/alex18101985/AnyKernel3.git AnyKernel3-master
          cd AnyKernel3-master
          cp ../kernel_platform/device/xiaomi/marble-kernel/Image .
          rm -r .git README.md
          find . -type f -name 'placeholder' -delete
          find . -type d -empty -delete
          zip -r9 "../kernel.zip" *
      - name: Generate release tag
        id: tag
        run: echo "release_tag=AOSPA_Marble_GKI_KSUNext_$(date +'%Y.%m.%d_%H%M')" >> "$GITHUB_OUTPUT"
      - name: Create release
        uses: softprops/action-gh-release@v2.6.1
        with:
          tag_name: ${{ steps.tag.outputs.release_tag }}
          files: |
            kernel.zip
      - name: Upload kernel artifact
        uses: actions/upload-artifact@v7.0.0
        with:
          name: kernel
          path: AnyKernel3-master/*
          compression-level: 9
